apiVersion: v1
kind: Service
metadata:
  name: catalog-api-service
  labels:
    app: catalog-api
spec:
  ports:
  - port: 80
    name: http
  type: ClusterIP
  selector:
    app: catalog-api

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: catalog-api
  template:
    metadata:
      labels:
        app: catalog-api
    spec:
      containers:
        - name: catalog
          image: fapiimages.azurecr.io/catalog-api-image:52
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      
      imagePullSecrets:
        - name: fapi-registry