version: "3.3"
services:
    basket-api:
      build:
        context: .
        dockerfile: "./Services/Basket/Basket.API/Dockerfile"
    catalog-api:
      build:
        context: .
        dockerfile: "./Services/Catalog/Catalog.API/Dockerfile"
    authentification-api:
      build:
        context: .
        dockerfile: "./Services/Authentification/Authentification.API/Dockerfile"